services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - ./ephemeris:/app/ephemeris
    environment:
      - PYTHON_ENV=development
      - EPHEMERIS_PATH=/app/ephemeris
      - LOG_LEVEL=DEBUG
    command: uvicorn run:app --host 0.0.0.0 --port 8000 --reload 